//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace LSR.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CheckSet
    {
        public long CheckId { get; set; }
        public Nullable<int> Type { get; set; }
        public Nullable<long> ItemId { get; set; }
        public Nullable<System.DateTime> CheckTime { get; set; }
        public Nullable<long> UserId { get; set; }
        public Nullable<System.DateTime> SubmitTime { get; set; }
        public string ContentText { get; set; }
    }
}
