//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace LSR.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class LSREntities : DbContext
    {
        public LSREntities()
            : base("name=LSREntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AdminSet> AdminSet { get; set; }
        public virtual DbSet<AlbumSet> AlbumSet { get; set; }
        public virtual DbSet<ArtistSet> ArtistSet { get; set; }
        public virtual DbSet<CheckSet> CheckSet { get; set; }
        public virtual DbSet<CommentSet> CommentSet { get; set; }
        public virtual DbSet<Music_MusicSheet_rel> Music_MusicSheet_rel { get; set; }
        public virtual DbSet<MusicSet> MusicSet { get; set; }
        public virtual DbSet<MusicSheetSet> MusicSheetSet { get; set; }
        public virtual DbSet<MVSet> MVSet { get; set; }
        public virtual DbSet<StyleSet> StyleSet { get; set; }
        public virtual DbSet<User_InfoSet> User_InfoSet { get; set; }
        public virtual DbSet<User_Music_Like_rel> User_Music_Like_rel { get; set; }
        public virtual DbSet<User_MusicSheet_rel> User_MusicSheet_rel { get; set; }
        public virtual DbSet<User_User_rel> User_User_rel { get; set; }
    }
}
