//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace LSR.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MusicSheetSet
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public MusicSheetSet()
        {
            this.Music_MusicSheet_rel = new HashSet<Music_MusicSheet_rel>();
            this.User_MusicSheet_rel = new HashSet<User_MusicSheet_rel>();
        }
    
        public long MusicSheetId { get; set; }
        public string Name { get; set; }
        public string Info { get; set; }
        public long UserId { get; set; }
        public System.DateTime SetDate { get; set; }
        public string Image { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Music_MusicSheet_rel> Music_MusicSheet_rel { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<User_MusicSheet_rel> User_MusicSheet_rel { get; set; }
        public virtual User_InfoSet User_InfoSet { get; set; }
    }
}
