//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace LSR.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class MusicSet
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public MusicSet()
        {
            this.CommentSet = new HashSet<CommentSet>();
            this.Music_MusicSheet_rel = new HashSet<Music_MusicSheet_rel>();
            this.MVSet = new HashSet<MVSet>();
            this.User_Music_Like_rel = new HashSet<User_Music_Like_rel>();
        }
    
        public long MusicId { get; set; }

        [Display(Name ="歌曲")]
        public string MusicName { get; set; }

        public long ArtistId { get; set; }

        
        public Nullable<long> AlbumId { get; set; }
        [Display (Name = "时长")]
        public Nullable<System.TimeSpan> MusicDuration { get; set; }
        public Nullable<System.DateTime> UploadDate { get; set; }
        public Nullable<long> UserId { get; set; }
        public Nullable<int> FileSize { get; set; }
        public string MusicStyle { get; set; }
        public string MusicLyrics { get; set; }
        public string MusicImage { get; set; }
        public string MusicFile { get; set; }
    
        public virtual AlbumSet AlbumSet { get; set; }
        public virtual ArtistSet ArtistSet { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CommentSet> CommentSet { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Music_MusicSheet_rel> Music_MusicSheet_rel { get; set; }
        public virtual User_InfoSet User_InfoSet { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MVSet> MVSet { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<User_Music_Like_rel> User_Music_Like_rel { get; set; }
    }
}
