//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace LSR.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MVSet
    {
        public long MVId { get; set; }
        public string Name { get; set; }
        public string Info { get; set; }
        public System.DateTime UploadDate { get; set; }
        public long UserId { get; set; }
        public long MusicId { get; set; }
        public string Image { get; set; }
        public string MVFile { get; set; }
        public Nullable<int> StyleId { get; set; }
        public Nullable<bool> IsChecked { get; set; }
        public Nullable<bool> IsAvailable { get; set; }
    
        public virtual MusicSet MusicSet { get; set; }
        public virtual StyleSet StyleSet { get; set; }
        public virtual User_InfoSet User_InfoSet { get; set; }
    }
}
