//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace LSR.Models
{
    using LSR.Common;
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class User_InfoSet
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public User_InfoSet()
        {
            this.CommentSet = new HashSet<CommentSet>();
            this.MusicSet = new HashSet<MusicSet>();
            this.MVSet = new HashSet<MVSet>();
            this.User_Music_Like_rel = new HashSet<User_Music_Like_rel>();
            this.User_MusicSheet_rel = new HashSet<User_MusicSheet_rel>();
            this.User_User_rel = new HashSet<User_User_rel>();
            this.Gender = "男";
            this.Phone = 0;
            this.Birthday = new DateTime(2022,1,1);
            this.UserName = "C" + DateTime.Now.Ticks;
        }
    
        public long UserId { get; set; }
        [Display(Name = "UserName")]
        [Required(ErrorMessage = "请填写用户名")]
        public string UserName { get; set; }
        [Required(ErrorMessage ="请输入密码")]
        [DataType(DataType.Password)]
        [Display(Name = "PassWord")]
        public string PassWord { get; set; }
        [Required(ErrorMessage ="请选择性别")]
        [Display(Name = "Gender")]
        public string Gender { get; set; }
        [DataType(DataType.EmailAddress)]
        [Required(ErrorMessage = "请输入电子邮箱")]
        [Display(Name = "UserEmail")]
        public string UserEmail { get; set; }
        [Display(Name = "Phone")]
        [Required(ErrorMessage = "请填写电话号码")]
        public Nullable<long> Phone { get; set; }

        [Display(Name = "Birthday")]
        [DataType(DataType.Date)]
        [DisplayFormat(DataFormatString = "{0:yyyy-MM-dd}", ApplyFormatInEditMode = true)]
        public Nullable<System.DateTime> Birthday { get; set; }
        [Display(Name ="Image")]
        public string Image { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CommentSet> CommentSet { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MusicSet> MusicSet { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MVSet> MVSet { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<User_Music_Like_rel> User_Music_Like_rel { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<User_MusicSheet_rel> User_MusicSheet_rel { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<User_User_rel> User_User_rel { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MusicSheetSet> MusicSheetSet { get; set; }

        internal EditUser Query()
        {
            var queryUser = new EditUser();
            queryUser.UserName = this.UserName;
            queryUser.Phone = (long)this.Phone;
            queryUser.Birthday = (DateTime)this.Birthday;
            queryUser.Gender = this.Gender;
            queryUser.UserEmail = this.UserEmail;
            return queryUser;
        }

        internal void Modified(User_InfoSet user)
        {
            this.UserName = user.UserName;
            this.Phone = user.Phone;
            this.Birthday = user.Birthday;
            this.Gender = user.Gender;
            this.Image = user.Image;
        }
    }
}
